-- Ongeza category 'tours' kwanza
insert into categories (key, title, emoji, tag) values ('tours', 'Tours na Safari', '🧭', 'Guided Experiences') on conflict (key) do nothing;

-- Ongeza vipengele 18 vya Tours
insert into listings (category_key, title, location, description, image_url, maps_link, whatsapp_number, status, partner_id) values
  ('tours', 'Stone Town Heritage Tour', 'Stone Town, Zanzibar', 'Step back in time exploring the rich cultural tapestry of Stone Town – a UNESCO World Heritage Site. Visit Forodhani Gardens, the Palace Museum, the Old Fort, and narrow historic alleyways adorned with intricately carved Omani wooden doors, with expert local guides.', 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=900&amp;h=600&amp;q=80', 'https://www.google.com/maps/search/?api=1&amp;query=-6.162222,39.1920735', null, 'approved', null),
  ('tours', 'Mnemba Atoll Snorkelling', 'Mnemba Island, North East Zanzibar', 'Snorkel and dive in the world-famous Mnemba Atoll Marine Conservation Area. One of the Indian Ocean''s most vibrant coral ecosystems – home to sea turtles, dolphins, and hundreds of tropical fish species.', '/images/tours/mnemba-atoll-snorkelling.jpeg', 'https://www.google.com/maps/search/?api=1&amp;query=-5.8204983,39.383505', '255717737357', 'approved', null),
  ('tours', 'Kidichi Spice Farm Tour', 'Spice Region, Central Zanzibar', 'Discover why Zanzibar is called the "Spice Island." Taste and smell fresh cloves, cinnamon, vanilla, nutmeg, cardamom and ylang-ylang directly from lush green plants. Combine with a visit to the historic Kidichi Persian Baths for a complete sensory and cultural journey.', '/images/tours/kidichi-spice-farm-tour.jpeg', 'https://www.google.com/maps/search/?api=1&amp;query=-6.090785899999999,39.2413537', '255777414461', 'approved', null),
  ('tours', 'Dhow Sunset Cruise', 'Nungwi / Stone Town Harbor', 'Sail on a traditional Zanzibari wooden dhow as the sun dips below the Indian Ocean horizon. A quintessential Zanzibar experience with sundowners, seafood snacks, and the golden light of an equatorial sunset painting the sky.', '/images/tours/dhow-sunset-cruise.jpeg', 'https://www.google.com/maps/search/?api=1&amp;query=-5.7229228999999995,39.3014952', '255672530415', 'approved', null),
  ('tours', 'Prison Island Excursion', 'Changuu Island, Zanzibar', 'Visit Changuu (Prison Island), a small island 5.6km northwest of Stone Town. Home to giant Aldabra tortoises, historic colonial buildings, and some of Zanzibar''s finest crystal-clear snorkelling waters just 20 minutes by boat.', '/images/tours/prison-island-excursion.jpeg', 'https://www.google.com/maps/search/?api=1&amp;query=-6.119531800000001,39.166396999999996', null, 'approved', null),
  ('tours', 'Jozani Forest & Red Colobus', 'Jozani-Chwaka Bay National Park', 'Visit Zanzibar''s only national park, home to the rare and endemic Zanzibar Red Colobus Monkey. Walk mangrove boardwalks through ancient mahogany forest, spot bushbabies and rare bird species on guided nature walks.', '/images/tours/jozani-forest-amp-red-colobus.jpeg', 'https://www.google.com/maps/search/?api=1&amp;query=-6.241557299999999,39.4139504', null, 'approved', null),
  ('tours', 'Kizimkazi Dolphin Tour', 'Kizimkazi, South Coast Zanzibar', 'Swim and snorkel alongside wild bottlenose and humpback dolphins in their natural habitat off Zanzibar''s south coast. The village of Kizimkazi is world-famous for dolphin sightings, with daily resident dolphin pods.', 'https://images.unsplash.com/photo-1591025207163-942350e47db2?w=900&amp;h=600&amp;q=80', 'https://www.google.com/maps/search/?api=1&amp;query=-6.4537162,39.4717759', '255672530415', 'approved', null),
  ('tours', 'Forodhani Night Food Tour', 'Forodhani Gardens, Stone Town', 'At sunset, Forodhani Gardens transforms into Zanzibar''s most vibrant open-air food market. Sample Zanzibar pizza, urojo soup, sugar cane juice, mishkaki grills, and fresh seafood with a local expert guide.', '/images/tours/forodhani-night-food-tour.jpeg', 'https://www.google.com/maps/search/?api=1&amp;query=-6.1603409,39.189002599999995', null, 'approved', null),
  ('tours', 'Safari Blue', 'Fumba, South West Zanzibar', 'Zanzibar''s most celebrated full-day sailing excursion. Sail a traditional dhow through mangroves, snorkel over coral gardens, visit a secluded sandbank for lunch, and return with sundowners. A complete Zanzibar ocean experience.', '/images/tours/safari-blue.jpeg', 'https://www.google.com/maps/search/?api=1&amp;query=Safari+Blue+Experience+Zanzibar', '255779773878', 'approved', null),
  ('tours', 'ZanTours', 'Stone Town, Zanzibar', 'One of Zanzibar''s longest-established and most reputable tour operators. Offering a full range of island excursions including spice tours, dolphin tours, snorkelling, cultural tours, and custom itineraries for independent travellers.', '/images/tours/zantours.jpeg', 'https://www.google.com/maps/search/?api=1&amp;query=ZanTours+Zanzibar', '255779600010', 'approved', null),
  ('tours', 'Chumbe Island Coral Park', 'Chumbe Island, South West Zanzibar', 'A world-renowned marine conservation area and eco-lodge on a pristine uninhabited island. Snorkel one of the most biologically diverse coral reef sanctuaries in East Africa. Day trips and overnight stays available.', '/images/tours/chumbe-island-coral-park.jpeg', 'https://www.google.com/maps/search/?api=1&amp;query=Chumbe+Island+Coral+Park+Zanzibar', '255777413232', 'approved', null),
  ('tours', 'Nakupenda Sandbank Tour', 'Nakupenda, Stone Town Waters', 'A breathtaking full-day excursion to a pristine, disappearing white sandbank rising from the turquoise Indian Ocean. Enjoy sunbathing, premium snorkelling among vibrant coral reefs, and a lavish beachside live-cooked seafood buffet as the tide swirls around you.', '/images/tours/nakupenda-sandbank-tour.jpeg', 'https://www.google.com/maps/search/?api=1&amp;query=Nakupenda+Beach+Zanzibar', '255717737357', 'approved', null),
  ('tours', 'Nungwi Turtle Aquarium & Village Tour', 'Nungwi, North Zanzibar', 'Visit the famous Mnarani Natural Aquarium in Nungwi — a tidal pool sanctuary home to endangered sea turtles rescued by the local community. Swim alongside the turtles, learn about the conservation programme, and explore the traditional fishing village of Nungwi with a local guide. A unique combination of marine conservation and authentic Zanzibari village life.', 'https://images.unsplash.com/photo-1591025207163-942350e47db2?w=700&amp;h=500&amp;q=80', 'https://www.google.com/maps/search/?api=1&amp;query=Mnarani+Aquarium+Nungwi+Zanzibar', null, 'approved', null),
  ('tours', 'Swahili Cooking Class', 'Stone Town, Zanzibar', 'An immersive hands-on Swahili cooking experience led by a local Zanzibari chef. Begin with a visit to the Darajani market to select fresh spices, coconut, and seafood. Then cook a traditional three-course Zanzibari meal — pilau, coconut fish curry, and cardamom tea — and sit down to enjoy the feast you''ve prepared. Perfect for food lovers and culture seekers.', 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=700&amp;h=500&amp;q=80', 'https://www.google.com/maps/search/?api=1&amp;query=Darajani+Market+Stone+Town+Zanzibar', null, 'approved', null),
  ('tours', 'Mangrove Kayaking & Eco Tour', 'Chwaka Bay, East Zanzibar', 'Paddle through the ancient mangrove forests of Chwaka Bay — one of East Africa''s most important coastal ecosystems. A local ecology guide leads you through winding waterways where kingfishers dart overhead, crabs scuttle below, and the canopy creates a cathedral of green. Includes a stop at a traditional fishing community and a beachside seafood lunch. A tranquil, off-the-beaten-track Zanzibar experience.', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=700&amp;h=500&amp;q=80', 'https://www.google.com/maps/search/?api=1&amp;query=Chwaka+Bay+Zanzibar', null, 'approved', null),
  ('tours', 'North Coast Full-Day Explorer', 'Nungwi · Kendwa · Matemwe', 'A guided full-day road trip along Zanzibar''s stunning north coast — the most scenic stretch of the island. Visit the postcard-perfect beaches of Nungwi and Kendwa, stop at the Nungwi Turtle Aquarium, explore the quiet coral-sand shores of Matemwe, and enjoy a fresh seafood lunch at a beachside grill. Includes air-conditioned transport, a knowledgeable local guide, and flexible stops along the route.', 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=700&amp;h=500&amp;q=80', 'https://www.google.com/maps/search/?api=1&amp;query=Nungwi+Beach+Zanzibar', null, 'approved', null),
  ('tours', 'Pemba Island Day Excursion', 'Pemba Island, Tanzania', 'Escape the crowds and discover Pemba — Zanzibar''s wilder, greener, and lesser-visited sister island. Famous among divers for its dramatic underwater walls and pristine reefs, Pemba also offers lush clove plantations, mangrove-lined creeks, and an authentic, unhurried pace of life. A day trip from Stone Town by light aircraft or speedboat. Ideal for divers, nature lovers, and travellers seeking the road less travelled.', 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=700&amp;h=500&amp;q=80', 'https://www.google.com/maps/search/?api=1&amp;query=Pemba+Island+Tanzania', null, 'approved', null),
  ('tours', 'Sunrise Fishing with Local Fishermen', 'Nungwi / Matemwe, Zanzibar', 'Set sail before dawn aboard a traditional Zanzibari ngalawa outrigger with local fishermen who have worked these waters for generations. Cast hand lines, watch the sun rise over the Indian Ocean in colours that defy description, and bring your catch back to shore for a fresh-grilled breakfast on the beach. An intimate, authentic glimpse into Zanzibari fishing life — far removed from tourist routes.', 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=700&amp;h=500&amp;q=80', 'https://www.google.com/maps/search/?api=1&amp;query=Nungwi+Beach+Zanzibar', null, 'approved', null);
